# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Favorites 
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED

          # Options
          user: NeiK0s496
          template: classic
          base: ""
          config_timezone: America/Mexico_City
          plugin_anilist: yes
          plugin_anilist_limit_characters: 33
          plugin_anilist_sections: characters
          plugin_anilist_shuffle: yes
          plugin_anilist_user: .user.login
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: .user.login
        
