# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Favorites anime and currently watching
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED

          # Options
          user: ZerAdam
          template: classic
          base: ""
          config_timezone: America/Mexico_City
          plugin_anilist: yes
          plugin_anilist_limit: 3
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime, manga, characters
          plugin_anilist_sections: favorites, watching
          plugin_anilist_shuffle: yes
          plugin_anilist_user: .user.login
        
